version: "2.3"

services:
    mariadb:
        image: mariadb:latest
        hostname: mariadb
        container_name: mariadb
        environment:
            MARIADB_ROOT_PASSWORD: rootpass
            MARIADB_DATABASE: slurm_acct_db
            MARIADB_USER: slurm
            MARIADB_PASSWORD: password
            TZ: "Europe/Paris"
        volumes:
            - mariadb:/var/lib/mariadb
        privileged: true
        networks: 
            - slurm

    slurm:
        image: slurm:latest
        hostname: slurm
        container_name: slurm
        privileged: true
        volumes:
            - munge:/etc/munge
            - slurm_log:/var/log/slurm
            - slurm_data:/var/lib/slurm
            - slurm_statesaveloc:/var/spool/SLURM
            - ./config/slurm:/etc/slurm
        expose:
            - "6819"
        depends_on:
            - mariadb
        networks: 
            - slurm

    c1:
        image: slurm:latest
        hostname: c1
        container_name: c1
        privileged: true
        volumes:
            - munge:/etc/munge
            - slurm_log:/var/log/slurm
            - slurm_data:/var/lib/slurm
            - ./config/slurm:/etc/slurm
        expose:
            - "6817"
        depends_on:
            - "slurm"
        networks: 
            - slurm

    c2:
        image: slurm:latest
        hostname: c2
        container_name: c2
        privileged: true
        volumes:
            - munge:/etc/munge
            - slurm_log:/var/log/slurm
            - slurm_data:/var/lib/slurm
            - ./config/slurm:/etc/slurm
        expose:
            - "6818"
        depends_on:
            - "slurm"
        networks:
            - slurm

    c3:
        image: slurm:latest
        hostname: c3
        container_name: c3
        privileged: true
        volumes:
            - munge:/etc/munge
            - slurm_log:/var/log/slurm
            - slurm_data:/var/lib/slurm
            - ./config/slurm:/etc/slurm
        expose:
            - "6818"
        depends_on:
            - "slurm"
        networks:
            - slurm

    c4:
        image: slurm:latest
        hostname: c4
        container_name: c4
        privileged: true
        volumes:
            - munge:/etc/munge
            - slurm_log:/var/log/slurm
            - slurm_data:/var/lib/slurm
            - ./config/slurm:/etc/slurm
        expose:
            - "6818"
        depends_on:
            - "slurm"
        networks:
            - slurm

networks:
  slurm:

volumes:
  mariadb:
  munge:
  slurm_log:
  slurm_data:
  slurm_statesaveloc:
